.devcontainer/devcontainer.json, .github/workflows/ci-dotnet.yml, .github/workflows/ci-go.yml, .github/workflows/ci-rust.yml, tools/deployment/README.md
Update remaining CI scripts to pass repository token
=> update remaining CI scripts

.github/workflows/ci-dotnet.yml, .github/workflows/ci-go.yml, .github/workflows/ci-rust.yml, .github/workflows/e2e-cross-language.yml
…d not the fork to access the action secret.
=> Add pull_request_target so the workflows are run successfully in fork

dotnet/src/Azure.Iot.Operations.Connector/TelemetryConnectorWorker.cs, dotnet/src/Azure.Iot.Operations.Mqtt/Session/MqttSessionClient.cs, dotnet/src/Azure.Iot.Operations.Mqtt/TokenRefreshTimer.cs, dotnet/src/Azure.Iot.Operations.Protocol/AkriSystemProperties.cs, dotnet/src/Azure.Iot.Operations.Protocol/Connection/X509ClientCertificateLocator.cs, dotnet/src/Azure.Iot.Operations.Services/Assets/Asset.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/IStateStoreClient.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreClient.cs, go/services/statestore/API.md, go/services/statestore/client.go, go/services/statestore/del.go, go/services/statestore/get.go, go/services/statestore/keynotify.go, go/services/statestore/reconnect.go, go/services/statestore/set.go, go/services/statestore/vdel.go, rust/azure_iot_operations_mqtt/src/session/session.rs, rust/azure_iot_operations_mqtt/src/session/state.rs
Logging changes
- Fix minor capitalization issues in rust logs
- Remove/rework some .NET logs that touch/may touch secrets
=> [.NET + Rust + Go] Minor logging changes, cleanup

eng/dtdl/aep-name-based-operations.json
=> [.NET] Update AEP DTDL

dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/AssetSpecification.cs, dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/DeviceRef.cs, dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/ModelsConverter.cs, dotnet/test/Azure.Iot.Operations.Services.UnitTests/AssetAndDeviceRegistry/ModelsConverterTests.cs
Add DeviceRef property to AssetSpecification and implement conversion
=> [.NET] Add DeviceRef property to AssetSpecification and implement conversion

rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/lib.rs
Optimized structs for Device operations.
Into/From traits not included in this PR
Discovery related structs not included in this PR
=> [Dev Branch] [Rust][ADR] Device structs

rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/azure_device_registry/client.rs
API stubs (the stubbiest of stubs) for the ADR Client to allow creating stubs for the Device operation APIs
API stubs for Device operations.
implementation not included in this PR
Discovery related API stubss not included in this PR
=> [Dev Branch] [Rust][ADR] Device API Stubs

rust/azure_iot_operations_services/src/azure_device_registry.rs
Froms implemented for AssetStatus and its child structs
=> [Rust][Services] Asset Status Impl From

rust/azure_iot_operations_services/src/azure_device_registry.rs
AssetUpdateObservation defined.
Froms implemented for classes belonging to adr_name_gen::AssetSpecificationSchema
=> [Rust][Services] : Observation of Asset and some Froms implemented for asset specification

rust/azure_iot_operations_services/src/azure_device_registry/client.rs
API signature for 4 APIs related to Asset.
=> [Rust][Services] :Asset APIs 

rust/azure_iot_operations_services/src/azure_device_registry.rs
This PR adds From<> impls for structs that need this for the API stubs
=> [Dev Branch] [Rust][ADR] Device structs from implementations

rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/azure_device_registry/client.rs
This PR adds scaffolding for the adr error and some errors as needed for impl so far.
Also adds implementations for creating device invokers and calling non-notify device APIs. Sample/validation to be in follow-up pr
=> [Dev Branch] [Rust][ADR] implementation for non-notify device apis and error in progress

rust/azure_iot_operations_services/Cargo.toml, rust/azure_iot_operations_services/examples/azure_device_registry_client.rs
confirmed runs locally. Doesn't run notification apis
=> [Dev Branch] [Rust][ADR] Sample that runs basic Device APIs

rust/azure_iot_operations_services/examples/azure_device_registry_client.rs, rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/azure_device_registry/client.rs, rust/azure_iot_operations_services/src/common.rs
This PR:
- simplifies some of the Asset structs
- cleans up the sample
- adds shutdown and unobserves to sample
- prettifies some logging
- removes a bunch of unnecessary From impls
=> [Dev Branch] [Rust][ADR] Cleanup

rust/azure_iot_operations_services/src/azure_device_registry.rs
This PR adds a few more derived impls for some of the structs needed to send status updates
=> [Dev Branch] [Rust][ADR] ADR struct derives

dotnet/samples/Connectors/EventDrivenTcpThermostatConnector/KubernetesResources/connector-template.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/KubernetesResources/connector-template.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/SampleRestServer/server.js, dotnet/samples/Connectors/PollingRestThermostatConnector/ThermostatStatusDatasetSampler.cs, dotnet/samples/Connectors/SqlConnector/KubernetesResources/connector-template.yaml, dotnet/src/Azure.Iot.Operations.Connector/Azure.Iot.Operations.Connector.csproj, dotnet/src/Azure.Iot.Operations.Mqtt/Azure.Iot.Operations.Mqtt.csproj, dotnet/src/Azure.Iot.Operations.Protocol/Azure.Iot.Operations.Protocol.csproj, dotnet/src/Azure.Iot.Operations.Services/Azure.Iot.Operations.Services.csproj
And bump versions for a preview release of these Akri bits
=> [.NET][Akri] Add replica field in connector samples, check for 401 errors when making HTTP requests

rust/azure_iot_operations_connector/examples/filemount_azure_device_registry_observation.rs, rust/azure_iot_operations_connector/src/filemount/azure_device_registry.rs
This PR brings over changes in #748 
The PR:
- Includes a fix for the file mount for ADR 
- The watcher is now triggered on a create, modify or deletion event and iterates over the mount directory to detect any changes.
- _Note: It is not possible to determine which file has changed as the mount is symlinked so events picked up by the watcher do not include the relevant file where changes were made._
- Verified against the ADR service
=> [Rust][Connector] Updating file mount with fix

rust/azure_iot_operations_connector/src/filemount/azure_device_registry.rs
=> [Rust][Connector] Syncing file mount changes from feature/akri to feature/rust-akri

.github/actions/configure-aio/action.yml
Signed-off-by: Ryan Winter <ryanwinter@outlook.com>
=> update to call action, rather than script directly.

dotnet/src/Azure.Iot.Operations.Mqtt/Azure.Iot.Operations.Mqtt.csproj, dotnet/src/Azure.Iot.Operations.Protocol/Azure.Iot.Operations.Protocol.csproj, dotnet/src/Azure.Iot.Operations.Services/Azure.Iot.Operations.Services.csproj
Services:
- Remove some unused option bundles from StateStore/LL/LE layer (#679)
- Fix bug where asset monitor didn't wait between polling (#673)
Protocol:
- Add support for error modeling in headers (#676)
- Add ReceiveMaximum configuration to MqttConnectionSettings (#697)
- Remove unused MQTT client option (#660)
MQTT:
- Add ReceiveMaximum configuration to MqttConnectionSettings (#697)
=> [.NET] Bump versions for 5/1/2025 release

dotnet/samples/Connectors/EventDrivenTcpThermostatConnector/KubernetesResources/connector-template.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/KubernetesResources/connector-template.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/KubernetesResources/rest-server-asset1-definition.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/KubernetesResources/rest-server-asset2-definition.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/KubernetesResources/rest-server-device-definition.yaml, dotnet/samples/Connectors/PollingRestThermostatConnector/RestThermostatDatasetSamplerFactory.cs, dotnet/samples/Connectors/PollingRestThermostatConnector/ThermostatStatusDatasetSampler.cs, dotnet/samples/Connectors/PollingRestThermostatConnector/deploy-connector-and-device.sh, dotnet/samples/Connectors/SqlConnector/KubernetesResources/connector-template.yaml, dotnet/samples/Connectors/SqlConnector/QualityAnalyzerDatasetSampler.cs, dotnet/samples/Connectors/SqlConnector/SqlQualityAnalyzerDatasetSamplerFactory.cs, dotnet/src/Azure.Iot.Operations.Connector/AdrClientWrapper.cs, dotnet/src/Azure.Iot.Operations.Connector/Assets/AssetFileMonitor.cs, dotnet/src/Azure.Iot.Operations.Connector/Assets/EndpointCredentials.cs, dotnet/src/Azure.Iot.Operations.Connector/Assets/FileUtilities.cs, dotnet/src/Azure.Iot.Operations.Connector/Assets/IAssetFileMonitor.cs, dotnet/src/Azure.Iot.Operations.Connector/DeviceContext.cs, dotnet/src/Azure.Iot.Operations.Connector/IAdrClientWrapper.cs, dotnet/src/Azure.Iot.Operations.Connector/IDatasetSamplerFactory.cs, dotnet/src/Azure.Iot.Operations.Connector/PollingTelemetryConnectorWorker.cs, dotnet/test/Azure.Iot.Operations.Connector.UnitTests/AssetFileMonitorTests.cs, dotnet/test/Azure.Iot.Operations.Connector.UnitTests/MockAdrClientWrapper.cs, dotnet/test/Azure.Iot.Operations.Connector.UnitTests/MockAssetFileMonitor.cs, dotnet/test/Azure.Iot.Operations.Connector.UnitTests/MockDatasetSamplerFactory.cs, eng/test/test-connector-mount-files/adr-resources/SomeDeviceName_SomeInboundEndpointName
Also update connector template yaml files to get up-to-date with newly required fields
Also update polling rest thermostat connector sample to use 2 assets so that we can more easily test multi-asset scenarios
=> [.NET][Akri] Get device credentials using relative paths from GetDevice call

rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/azure_device_registry/device_name_gen/adr_base_service/asset_dataset_schema_element_schema.rs
Dtdl for ADR was updated in #780
Adds dataset configuration field to Dataset struct
=> [Rust][Services] Adding dataset configuration to dataset struct

dotnet/eng/test/test-adr-resources/coap-asset.yaml, dotnet/eng/test/test-adr-resources/my-thermostat-device.yaml, dotnet/eng/test/test-adr-resources/rest-asset.yaml
=> Add test resources

dotnet/templates/EventDrivenTelemetryConnector/EventDrivenTelemetryConnector.csproj, dotnet/templates/EventDrivenTelemetryConnector/MessageSchemaProvider.cs, dotnet/templates/EventDrivenTelemetryConnector/Program.cs, dotnet/templates/EventDrivenTelemetryConnector/TemplateConnectorWorker.cs, dotnet/templates/PollingTelemetryConnector/DatasetSampler.cs, dotnet/templates/PollingTelemetryConnector/DatasetSamplerFactory.cs, dotnet/templates/PollingTelemetryConnector/MessageSchemaProvider.cs, dotnet/templates/PollingTelemetryConnector/PollingTelemetryConnectorTemplate.csproj, dotnet/templates/PollingTelemetryConnector/Program.cs
They previously targeted main branch released bits which are obsolete now
=> [.NET] Make connector templates target feature branch package bits

dotnet/test/Azure.Iot.Operations.Services.IntegrationTests/AdrServiceClientIntegrationTests.cs, rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/azure_device_registry/client.rs
=> [Rust][Services] ADR unit tests

rust/azure_iot_operations_services/examples/adr_discovery.rs, rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/src/azure_device_registry/models/asset.rs, rust/azure_iot_operations_services/src/azure_device_registry/models/device.rs
(ignore my branch name, guess I was on autopilot)
This PR:
- updates the ADR Client with the latest 6/5 DTDL. Description updates from this DTDL will be added in the descriptions PR (#856 ) all together
=> [Rust][Services] ADR Client 6/5 DTDL Update

.github/workflows/ci-rust.yml, eng/test/test-adr-resources/rest-asset-for-update.yaml, eng/test/test-adr-resources/thermostat-device-for-update.yaml, rust/azure_iot_operations_services/src/azure_device_registry.rs, rust/azure_iot_operations_services/tests/azure_device_registry_client_tests.rs
adds adr integration tests. Currently has build errors bc the integration tests need to be updated - will fix these in a separate PR so that the changes are clearer
=> Merge feature/akri into feature/adr-6-2-update

rust/azure_iot_operations_protocol/src/rpc_command/invoker.rs
Problem:
One invoke request taking a long time can cause other concurrent requests to not receive their responses because of the lagging receiver problem. The invoker subscribes to the response broadcast channel before it pubs it's request. This makes sense, since it wants to be subscribed before it's ever possible for the response to come in. However, this means that if the publish takes a long time, it isn't recv'ing on its broadcast receiver, causing the lag.
The fix:
The pub completion and checking response publishes now happen concurrently in a tokio try_join!. If the puback takes a long time to receive, broadcast subscription is still being processed, even though the responses will likely not be for this request. A failure in either task will return an error immediately, same as the …
=> [Rust][Protocol] Fix lagging receiver on concurrent invokes with long puback

codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/communication/rust/Project/t4/RustCargoToml.tt, rust/azure_iot_operations_connector/Cargo.toml, rust/azure_iot_operations_protocol/Cargo.toml, rust/azure_iot_operations_services/Cargo.toml
connector: 0.1.0-alpha.4 -> 0.1.0-alpha.5
services: 0.9.0-alpha.3 -> 0.9.0-alpha.4
protocol: 0.10.0-alpha.1 -> 0.10.0-alpha.2
=> [Rust] Version Bump for 06-11-25 alpha release

.github/workflows/ci-dotnet.yml, .github/workflows/run-codegen.yml
The documentation for this action suggests that providing this token helps avoid rate limiting from Github
https://github.com/arduino/setup-protoc?tab=readme-ov-file#usage
=> [.NET] Provide github token to Protoc install step

codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/communication/rust/Project/t4/RustCargoToml.tt, rust/azure_iot_operations_connector/Cargo.toml, rust/azure_iot_operations_mqtt/Cargo.toml, rust/azure_iot_operations_protocol/Cargo.toml, rust/azure_iot_operations_services/Cargo.toml
`mqtt` 0.10.0-alpha.1 -> 0.10.0
`protocol` 0.10.0-alpha.2 -> 0.10.0
`services` 0.9.0-alpha.4 -> 0.9.0
`connector` 0.1.0-alpha.5 -> 0.1.0
=> [Rust][MQTT][Protocol][Services][Connector] Version bump for 07-24-25 release

rust/sample_applications/sample_connector_scaffolding/Cargo.toml, rust/sample_applications/sample_connector_scaffolding/src/main.rs
Connector crate 0.1.0 -> 0.3.0
Protocol crate 0.10.0 -> 0.12.0
=> [Rust][Scaffolding] Updating Rust polling scaffolding

dotnet/samples/Connectors/PollingRestThermostatConnector/deploy-connector-and-device.sh, dotnet/samples/Services/LeasedLockClient/Program.cs, dotnet/samples/Services/PassiveReplication/PassiveReplicationNode.cs, dotnet/samples/Services/StateStoreClient/Program.cs, dotnet/samples/applications/EventDrivenApp/InputWorker.cs, dotnet/samples/applications/EventDrivenApp/OutputWorker.cs, dotnet/src/Azure.Iot.Operations.Connector/AdrClientWrapper.cs, dotnet/src/Azure.Iot.Operations.Connector/ConnectorWorker.cs, dotnet/src/Azure.Iot.Operations.Connector/Files/AssetFileMonitor.cs, dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LeasedLockClient.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/IStateStoreClient.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/IStateStoreDeleteResponse.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/IStateStoreGetResponse.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/IStateStoreResponse.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/IStateStoreSetResponse.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreClient.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteResponse.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreGetResponse.cs, dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreSetResponse.cs, dotnet/test/Azure.Iot.Operations.Services.IntegrationTests/LeaderElectionClientIntegrationTests.cs, dotnet/test/Azure.Iot.Operations.Services.IntegrationTests/LeasedLockClientIntegrationTests.cs, dotnet/test/Azure.Iot.Operations.Services.IntegrationTests/StateStoreClientIntegrationTests.cs, dotnet/test/Azure.Iot.Operations.Services.UnitTests/LeasedLock/LeasedLockClientTests.cs, eng/test/schema-registry/src/Azure.Iot.Operations.Services.SchemaRegistry.Host/SchemaRegistryService.cs
=> [.NET] Add interfaces for state store client types to enable mocking the client
