- dotnet/src/Azure.Iot.Operations.Services/Azure.Iot.Operations.Services.csproj
This is a minimal release but contains one change that is needed for the connector package to take a nuget.org reference on it rather than a local reference
> [.NET] Bump version for services release

- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/communication/rust/Project/t4/RustLib.tt
Struct fields come from DTDL - we cannot change them. Clippy should not complain
> [Rust][Codegen] Suppress clippy lint for struct field names

- dotnet/src/Azure.Iot.Operations.Connector/Azure.Iot.Operations.Connector.csproj
This is a bit of a work around for managing packages in both nuget.org and our preview nuget feed.
The plan is for us to have connector package 0.10.1 still live in the preview feed, but have it take a dependency on the strongly signed (and publicly released) SDK nuget packages. Previously, the connector package depended on _unsigned_ 0.10.0 version packages, and those aren't published anywhere.
Also bump connector package version to 0.10.1
> [.NET] Make connector package target the strongly signed SDK packages

- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-go.yml
- .github/workflows/ci-markdown.yml
- .github/workflows/ci-rust.yml
- .github/workflows/e2e-cross-language.yml
Workflows run from forks, show up with a github.ref as `refs/heads/main` which mean forks will collide with each other, and workflows running from main and will be cancelled.
Try using github.head_ref first (a PR value), and fallback to github.ref if it doesnt exist.
> Dont cancel workflows run from forks

- rust/azure_iot_operations_services/src/common.rs
- rust/azure_iot_operations_services/src/lib.rs
- rust/azure_iot_operations_services/src/state_store/client.rs
- Extracted dispatching logic used in State Store for future re-use in ADR
- Changed `state_store::Client::observe()` to return an Error if attempting to observe a key that was not unobserved
- Modified logging for edge cases to `warn!`
> [Rust][Services] Extracted dispatching logic for re-use

- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/gen.sh
Codegen doesn't use .NET 8 anymore
> [.NET] Update ADR gen.sh to use .NET 9 build of codegen

- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/Asset.cs
- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/AssetDatasetSchemaElement.cs
- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/AssetEventSchemaElement.cs
- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/ModelsConverter.cs
* Use required C# keyword for `Name` and `Specification` fields in `Asset` class
* Use required C# keyword for `Name` field in `AssetDatasetSchemaElement` class
* Use required C# keyword for `EventNotifier` field in `AssetEventSchemaElement` class
> [.Net] Fix discrepancies between the nullability of some fields

- eng/dtdl/device-name-based-operations.json
This pull request introduces several updates to the `eng/dtdl/device-name-based-operations.json` file to enhance the device operations schema. Key changes include the addition of new fields and objects, updates to existing field names and types, and corrections to identifiers for consistency.
* Added a new `DeviceOutboundEndpoint` object with fields `address` and `endpointType` to support outbound device operations.
* Introduced new fields such as `assetTypeRefs` (array of strings) and `actionType` (enum with values `Read`, `Write`, and `Call`) to extend schema functionality. [[1]](diffhunk://#diff-41088b318f21bdb9b38e5bd8690bfaf97940a0fe427a9e1701ada8d6245b83d4R524-R531) [[2]](diffhunk://#diff-41088b318f21bdb9b38e5bd8690bfaf97940a0fe427a9e1701ada8d6245b83d4L902-R971)
* Added an …
> [.Net] DTDL updated

- rust/azure_iot_operations_services/examples/azure_device_registry_client.rs
- rust/azure_iot_operations_services/src/azure_device_registry.rs
- rust/azure_iot_operations_services/src/azure_device_registry/client.rs
Adds implementation for:
Device update observe
Device update unobserve
recv notifications loop
Updates:
- some errors needed by the observation/notification flows
- adds shutdown notifier used by the notification receiver
- calls shutdown notifier from shutdown
- synchronizes some naming/logic between device and asset implementations
- pulls some common code/strings into consts and helper functions
> [Dev Branch] [Rust][ADR] Device observe/unobserve/telemetry receiver

- eng/test/test-connector-mount-files/connector-config-no-auth-no-tls/AIO_METADATA
- eng/test/test-connector-mount-files/connector-config-no-auth-no-tls/DIAGNOSTICS
- eng/test/test-connector-mount-files/connector-config-no-auth-no-tls/MQTT_CONNECTION_CONFIGURATION
- eng/test/test-connector-mount-files/connector-config/AIO_METADATA
- eng/test/test-connector-mount-files/connector-config/DIAGNOSTICS
- eng/test/test-connector-mount-files/connector-config/MQTT_CONNECTION_CONFIGURATION
Previously they used UTF-8 BOM which was unnecessary and problematic.
Also fixed incorrect capitalization on an enum
> Fix filemount test files to use UTF-8

- .github/pages/docfx.json
- dotnet/src/Azure.Iot.Operations.Services/Azure.Iot.Operations.Services.csproj
The csproj file for the Connector package will only include dependencies if the "Configuration" is set to Debug or Release.
Add Debug configuration target to the docfx.json file.
> Add Debug target for docfx otherwise it wont find dependencies for the Connector package

- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Array/code/ArrayAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Array/t4/ArrayAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Command/code/CommandAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Command/t4/CommandAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Enum/t4/EnumAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Map/code/MapAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Map/t4/MapAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Nullable/code/NullableAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Nullable/t4/NullableAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Object/code/ObjectAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Object/code/ResultAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Object/t4/ObjectAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Object/t4/ResultAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Telemetry/code/TelemetryAvroSchema.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/Telemetry/t4/TelemetryAvroSchema.tt
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/serialization/common/AvroSchemaSupport.cs
- codegen/src/Azure.Iot.Operations.ProtocolCompiler/TypeGenerator/AvroSchemaStandardizer.cs
The ProtocolCompiler failed to deduplicate embedded type definitions when generating AVSC files, which could result in invalid schema definitions.  This change fixes the problem by ensuring that each definition is included in the AVSC file only once.
> Fix AVRO codegen when type is repeated

- eng/dtdl/device-name-based-operations.json
There was a missing datasetConfiguration field in the ADR dtdl. for a dataset object Added relevant folks working on ADR. 
This would affect: #761 and #778 I believe
> [ADR] Missing dataSetConfiguration dtdl

- rust/azure_iot_operations_connector/examples/filemount_azure_device_registry_observation.rs
- rust/azure_iot_operations_connector/src/filemount/azure_device_registry.rs
Assets in files mounted by ADR are no longer delimited by `;` and are instead separated by newline.
- file mount client now uses `\n` as a delimiter for asset names in files
> [Rust][Connector] Changing from ; delineation to newline

- rust/azure_iot_operations_connector/Cargo.toml
- rust/azure_iot_operations_connector/examples/connector_get_adr_definitions.rs
- rust/azure_iot_operations_connector/examples/connector_get_adr_definitions_resources/connector_template.yaml
- rust/azure_iot_operations_connector/examples/connector_get_adr_definitions_resources/rest-thermostat-asset-definition.yaml
- rust/azure_iot_operations_connector/examples/connector_get_adr_definitions_resources/thermostat-device-definition.yaml
- rust/azure_iot_operations_connector/src/base_connector/managed_azure_device_registry.rs
- rust/azure_iot_operations_connector/src/data_transformer.rs
- rust/azure_iot_operations_connector/src/destination_endpoint.rs
This PR:
- updates the azure_iot_operations_connector crate to point to the adr client in feature/akri instead of pointing to feature/rust-akri now that changes have been merged to feature/akri
- updates connector crate and sample to align with slight adr client API changes
- updates connector resources to work with the latest operator/adr service
> [Rust] Update feature/akri to use latest adr client

- rust/azure_iot_operations_services/Cargo.toml
- rust/azure_iot_operations_services/examples/leased_lock_client.rs
- rust/azure_iot_operations_services/examples/lock_client.rs
- rust/azure_iot_operations_services/src/leased_lock.rs
- rust/azure_iot_operations_services/src/leased_lock/client.rs
- rust/azure_iot_operations_services/src/leased_lock/lease.rs
- rust/azure_iot_operations_services/src/leased_lock/lock.rs
- rust/azure_iot_operations_services/src/lib.rs
- rust/azure_iot_operations_services/src/state_store.rs
- rust/azure_iot_operations_services/src/state_store/client.rs
- rust/azure_iot_operations_services/tests/lease_client_tests.rs
- rust/azure_iot_operations_services/tests/lock_client_tests.rs
According to ADR 20 this leased lock client should be split into two layers, lease and lock clients. The lease client will have the bulk of logic for acquiring, renewing and releasing a key. The lock layer will present the expected semantics for locking operations.
Additionally auto-renewal of leases was not yet implemented in the leased lock client. included in this PR is the logic to perform the auto-renewal of leases/locks.
> [Rust][Services] Split leased_lock client (ADR 20) and add lease & lock auto-renewal

- .github/workflows/e2e-cross-language.yml
I'm seeing this pipeline timeout more often now that the AIO installation step itself can take ~10 minutes
> Make cross language pipeline timeout more generous

- codegen/src/Azure.Iot.Operations.ProtocolCompiler/EnvoyGenerator/EnvoyTransformFactory.cs
One-line fix to Rust code generation when using both CLI --shared option and Result co-type
> Fix interaction between NormalResult and shared namespace

- dotnet/samples/Connectors/EventDrivenTcpThermostatConnector/Program.cs
- dotnet/samples/Connectors/PollingRestThermostatConnector/Program.cs
- dotnet/samples/Connectors/SqlConnector/Program.cs
- dotnet/src/Azure.Iot.Operations.Connector/Configurations/ConnectorFileMountSettings.cs
These hardcoded client ids were just used while we waited on the Akri operator to deploy connectors with their actual client Ids.
> [.NET][Akri] Remove placeholder client ids

- rust/azure_iot_operations_connector/src/filemount/connector_config.rs
- rust/azure_iot_operations_connector/tests/artifact_tests.rs
Subset of changes in #809 that are immediately required, as #809 is blocked pending a spec alignment issue.
> [Rust][Connector] Rename env variable in `ConnectorConfiguration`

- dotnet/src/Azure.Iot.Operations.Connector/ConnectorWorker.cs
Don't use Trace inside a sample, use the provided logger instead.
This call to Trace also threw because it expected a different argument format, but now the log statement executes without throwing
> [.NET][Akri] Fix log statement

- dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedResponse.cs
#676 deleted this static constructor, but apparently code gen still needs it
> [.NET] Re-add static constructor for ExtendedResponse

- dotnet/test/Azure.Iot.Operations.Services.IntegrationTests/AdrServiceClientIntegrationTests.cs
This pull request enhances the integration tests in `AdrServiceClientIntegrationTests.cs` by adding new test cases and helper methods to improve coverage and functionality for device-related operations. The most important changes include adding tests for error handling and discovered device creation, as well as introducing a helper method to create requests for discovered devices.
* **Error handling**: Added a test case `GetDeviceThrowsAkriServiceErrorExceptionWhenDeviceNotFoundAsync` to verify that an appropriate exception is thrown when attempting to fetch a non-existent device.
* **Discovered device creation**: Added a test case `CanCreateOrUpdateDiscoveredDeviceAsync` to validate the creation or update of discovered devices, ensuring the response contains a valid `DiscoveryId`.
* …
> [.Net] Integration tests

- rust/azure_iot_operations_protocol/src/common/user_properties.rs
- rust/azure_iot_operations_protocol/src/rpc_command/executor.rs
- rust/azure_iot_operations_protocol/src/rpc_command/invoker.rs
- rust/azure_iot_operations_protocol/tests/command_network_tests.rs
Implementation of https://github.com/Azure/iot-operations-sdks/blob/main/doc/dev/adr/0021-error-modeling-headers.md in the AIO Rust RPC client.
> [Rust][Protocol] Add user-defined props AppErrorCode and AppErrorPayload to RPC

- rust/azure_iot_operations_services/examples/adr_device_asset.rs
Service is now not failing for the new APIs (if seems like a few things still aren't complete, but it's just around what gets replaced vs merged on status updates, so doesn't completely block this sample)
> [Rust] [Services] Enable full ADR Sample

- rust/azure_iot_operations_services/tests/azure_device_registry_client_tests.rs
This PR:
- updates ADR network tests with changes from new ADR DTDL:
- StatusConfig -> ConfigStatus
- specification vs status being different
- adds network tests for new APIs added in the DTDL update (get_device_status and get_asset_status)
Although the CI can't run until the connector crate changes are in, I have verified these tests run successfully locally
> [Rust] [Services] Update ADR network tests for ADR DTDL 6-2/6-5 updates

- rust/azure_iot_operations_connector/src/filemount/connector_artifacts.rs
- rust/azure_iot_operations_connector/tests/artifact_tests.rs
* Added support for the new `CONNECTOR_NAMESPACE` environment variable
* Renamed the `ADDITIONAL_CONFIGURATION` file to `ADDITIONAL_CONNECTOR_CONFIGURATION` in the `CONNECTOR_CONFIGURATION_MOUNT_PATH` filemount
* Renamed the `DEVICE_ENDPOINT_TLS_TRUST_BUNDLE_CACERT_MOUNT_PATH` to `DEVICE_ENDPOINT_TLS_TRUST_BUNDLE_CA_CERT_MOUNT_PATH` (added an underscore)
> [Rust][Connector] Fixes to ConnectorArtifacts to align with contract

- rust/azure_iot_operations_connector/Cargo.toml
- rust/azure_iot_operations_services/Cargo.toml
`services`: `0.9.0-alpha.2` -> `0.9.0-alpha.3`
`connector`: `0.1.0-alpha.2`  -> `0.9.0-alpha.3`
> [Rust][Services][Connector] Version Bump for 05-10-25 alpha release

- rust/azure_iot_operations_connector/Cargo.toml
connector: 0.1.0-alpha.3 -> 0.1.0-alpha.4
> [Rust][Services][Connector] Version Bump for 06-11-25 alpha release

- rust/azure_iot_operations_services/src/common.rs
- rust/azure_iot_operations_services/src/state_store/client.rs
Currently this PR only serves the main branch where only the state store client is present. 
More changes will be present on ADR client. There is a specific case where we need clone on the H (key) as well.
The resolution I got there is to do.  
```rust
/// Returns all currently tracked receiver ids
/// Note: This method requires Clone for H since it needs to return owned values
pub fn get_all_receiver_ids(&self) -> Vec<H> 
where
H: Clone,
{
let tx_map = self.tx_map.lock().unwrap();
tx_map.keys().cloned().collect()
}
```
> [Rust][Services] Hashable key in Dispatcher

- rust/azure_iot_operations_protocol/src/rpc_command/invoker.rs
Re-opened from #900 because of branch issues
Cherry pick of https://github.com/Azure/iot-operations-sdks/pull/893 plus additional fix needed
Problem:
One invoke request taking a long time can cause other concurrent requests to not receive their responses because of the lagging receiver problem. The invoker subscribes to the response broadcast channel before it pubs it's request. This makes sense, since it wants to be subscribed before it's ever possible for the response to come in. However, this means that if the publish takes a long time, it isn't recv'ing on its broadcast receiver, causing the lag.
The fix:
The pub completion and checking response publishes now happen concurrently in a tokio try_join!. If the puback takes a long time to receive, broadcast subscription is still being …
> [Rust][Protocol] Fix lagging receiver on concurrent invokes

- rust/azure_iot_operations_connector/src/base_connector/managed_azure_device_registry.rs
This PR:
- Addresses a bug where receiving a notification on an asset or dataset would not get fully processed if the receive flow was cancelled.
- Example: If receiving in a select branch and while processing the asset update a different branch takes over, we will lose the update.
- Changes unobserve to happen in a separate task.
> [Rust][Connector] Making receiving of Asset / Dataset notifications cancellable

- rust/azure_iot_operations_connector/src/deployment_artifacts/azure_device_registry.rs
Allows underscores to be used in inbound endpoint names
Tested with rest connector.
> [Rust][Connector] Allowing underscores to be used in inbound endpoint names

- rust/azure_iot_operations_connector/src/base_connector/managed_azure_device_registry.rs
This PR ensures that statuses that need to be reported in recv_notification functions are cancel safe. For the Asset recv_notification function, this means that we don't do any mutable actions until we can no longer be cancelled, and then do the mutable actions at that point. For the dataset recv_notification function, we spawn reporting the status into its own task so that it doesn't introduce a cancellation point.
> [Rust][Connector] Cancel Safe Status Reporting

- rust/azure_iot_operations_connector/src/base_connector.rs
- rust/azure_iot_operations_connector/src/base_connector/managed_azure_device_registry.rs
- rust/azure_iot_operations_connector/src/deployment_artifacts/azure_device_registry.rs
- rust/azure_iot_operations_connector/tests/artifact_tests.rs
- rust/azure_iot_operations_mqtt/src/session/receiver.rs
- rust/azure_iot_operations_protocol/src/common/aio_protocol_error.rs
- rust/azure_iot_operations_protocol/src/rpc_command/executor.rs
- rust/azure_iot_operations_protocol/src/telemetry/sender.rs
- rust/azure_iot_operations_protocol/tests/metl/command_invoker_tester.rs
- rust/azure_iot_operations_protocol/tests/metl/mqtt_hub.rs
- rust/azure_iot_operations_protocol/tests/metl/telemetry_sender_tester.rs
- rust/azure_iot_operations_protocol/tests/metl/test_payload.rs
- rust/sample_applications/event_driven_app/output_client/src/main.rs
Did a quick pass with [Clippy Lint Redundant Clone](https://rust-lang.github.io/rust-clippy/master/#redundant_clone) set to warn and fixed all of the correct warnings that came up. We can't leave this on by default because it isn't super stable and detects some needed clones, but can be used as a local tool to help with reducing extra `clone()`s. Note that this also doesn't catch everything, so there may be more that could be cleaned up, and this still needs to be manually thought about, even if this warning is on
> [Rust] Clean up Redundant Clones

- rust/azure_iot_operations_connector/README.md
- rust/azure_iot_operations_connector/examples/base_connector_sample.rs
- rust/azure_iot_operations_connector/src/base_connector.rs
Partial solution to the problem of artifact portability.
May need to combine connector arguments into some kind of context or options, depending on the eventual OTEL metrics integration.
Also still need to unify ADR artifacts with everything else.
> [Rust][Connector] Make `BaseConnector` ingest `ConnectorArtifacts`

- dotnet/templates/EventDrivenTelemetryConnector/TemplateConnectorWorker.cs
our samples use this method as well, though they are functionally identical
> [.NET][Akri] Make template use "RunConnectorAsync"

- rust/azure_iot_operations_connector/src/base_connector/managed_azure_device_registry.rs
- rust/azure_iot_operations_connector/src/lib.rs
This change factors out the schema reference reporting from the schema registration, to support scenarios where a dataset's schema has already been registered externally.
> [Rust] Add report_message_schema_reference

- dotnet/src/Azure.Iot.Operations.Protocol/AkriSystemProperties.cs
- dotnet/src/Azure.Iot.Operations.Protocol/RPC/CommandExecutor.cs
- dotnet/src/Azure.Iot.Operations.Protocol/RPC/CommandResponseCache.cs
- dotnet/src/Azure.Iot.Operations.Protocol/RPC/ICommandResponseCache.cs
- dotnet/test/Azure.Iot.Operations.Protocol.UnitTests/CommandResponseCacheUnitTests.cs
The cache APIs included parameters for the sourceId of a request, but it was unused in the cache implementation
> [.NET] SourceId documentation, remove unused references in RPC cache layer

- dotnet/src/Azure.Iot.Operations.Connector/Files/AssetFileMonitor.cs
- eng/test/test-connector-mount-files/adr-resources/..2025_22_7
- eng/test/test-connector-mount-files/adr-resources/..data
Any file in the adr resources folder that starts with ".." such as "..data" shouldn't be read as a device file
Add some example symlink files to the unit test directory that contains the actual device file we test with. Existing tests already validate the number of expected devices, so no change is needed in the unit tests themselves
> [.NET][Akri] Make asset file monitor filter out symlink files

- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/DiscoveredAsset.cs
- dotnet/src/Azure.Iot.Operations.Services/AssetAndDeviceRegistry/Models/ProtocolConverter.cs
The other similar fields were converted to strings a while ago, but I missed this one.
> [.NET][Akri] Fix DAsset action configuration field still being a JsonDocument

- codegen/src/Azure.Iot.Operations.ProtocolCompiler/T4/communication/rust/Command/t4/RustCommandExecutor.tt
- Cacheable duration no longer exists in the command executor options resulting in generated code that doesn't compile. Removing the generation in codegen.
> [Codegen][Rust] Removing cacheable duration from generated code

- rust/azure_iot_operations_connector/Cargo.toml
- rust/azure_iot_operations_services/Cargo.toml
`services` 0.10.0 -> 0.11.0
`0.10.0` is an invalid version of the services crate.
In #969 
`protocol` 0.10.0 -> 0.11.0
In #968 
`services` 0.9.0 -> 0.10.0
`connector` 0.1.0 -> 0.2.0
> [Rust][Services][Connector][Protocol] Version bump for 07-30-25 release

- rust/azure_iot_operations_connector/Cargo.toml
- rust/azure_iot_operations_services/Cargo.toml
- rust/ci/build-deps.sh
- rust/sample_applications/sample_connector_scaffolding/Cargo.toml
Problem:
cargo machete wasn't running properly because the version we had didn't work with rust 2024 edition
Fix:
update to newer cargo machete version and update unused deps that it now catches
> [Rust][CI] fix machete version and remove unused deps

- rust/sample_applications/sample_connector_scaffolding/Cargo.toml
- rust/sample_applications/sample_connector_scaffolding/src/main.rs
Scaffolding was using both `env_logger` and `azure_iot_operations_otel` which would clash
> [Rust][Scaffolding] Removed outdated logging

- doc/akri_connector/connector-metadata-schema.json
The MQTT connector does not support any dataset/event/stream/etc modeling, so our schema should allow for that
> [Connector metadata] Do not require any supported modeling

- eng/dtdl/adr-base-service.json
- rust/azure_iot_operations_connector/src/base_connector/managed_azure_device_registry.rs
- rust/azure_iot_operations_services/src/azure_device_registry/adr_base_gen/adr_base_service/x509credentials_schema.rs
- rust/azure_iot_operations_services/src/azure_device_registry/models/device.rs
This PR incorporates changes to ADR which add a separate key and intermediate certificate as optional fields when specifying authentication as x509Certificate.
> [Rust][Connector][Services] Integrate new separate key and intermediate cert secret

- tools/statestore-cli/Dockerfile
Update Statestore-cli Dockerfile to use cargo registry token for auth.
> Update Statestore-cli Dockerfile to use cargo registry token for auth
